theme: minima
title: Joshua Ho's Website
description: A virtual proof that I'm awesome

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"

social-network-links:
  rss: true
  email: "someone@example.com"
  linkedin: joshua-ho-5790
